@startuml Brick_Breaker

class Juego
class Barra
class Ladrillos
class Pelota
class Colisionable
class Jugador
class Vida


Juego o-- Ladrillos
Juego o-- Jugador
Ladrillos o-- Colores
Jugador o-- "3" Vida

Jugador *-- Juego
Jugador *-- "1" Barra 
Barra *-- "1"Pelota
Barra *-- "3"Vida
Jugador *-- "3"Vida

Pelota --|> Colisionable
Ladrillos --|> Colisionable


@enduml